
name: "Check publiccode.yml"

on: [push, pull_request]

jobs:
  publiccode_validation:
    runs-on: ubuntu-latest
    name: publiccode validation
    steps:
    - uses: actions/checkout@v2
    - uses: italia/publiccode-parser-action
      with:
        publiccode: 'publiccode.yml' # relative path to your publiccode.yml
